version: "3.1"
services:
  travelmongo:
    image: mongo:latest
    container_name: "travelmongo"
    ports:
      - 27017:27017
  hotel-service:
    image: subhamkrgupta/hotel-service:1.0
    container_name: "hotel-service"
    ports:
      - 8001:8001
    links:
      - travelmongo