
server:
  port: 8001

spring:
  data:
    mongodb:
      database: hotel
      host: localhost        #travelmongo
      port: 27017

  application:
    name: HOTEL-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
